FROM postgres:18.0

# COPY ./src/main/resources/content /var/lib/postgresql/content

# extensions
# RUN echo "CREATE EXTENSION IF NOT EXISTS ltree;" > /docker-entrypoint-initdb.d/ltree_ext.sql
# RUN echo "CREATE EXTENSION IF NOT EXISTS pg_trgm;" > /docker-entrypoint-initdb.d/pg_trgm_ext.sql
# RUN echo "CREATE EXTENSION IF NOT EXISTS tsm_system_rows;" > /docker-entrypoint-initdb.d/tsm_system_rows_ext.sql
